blank_issues_enabled: false
contact_links:
  - name: 项目讨论区
    url: https://discord.gg/6GFtSjfdF7
    about: 请在这里讨论项目相关话题
  - name: 项目文档
    url: https://gitee.com/Giab/GDDataForge/wikis
    about: 查看项目文档
